name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set version to var version
      run: version="${{ github.run_number }}"
    - name: update version to POM file
      run: sed -i 's/<version>.*<\/version>/<version>1.0.$version<\/version>/' pom.xml

    
    - name: Build the Docker image
      run: docker build --build-arg VERSION=$version . --file Dockerfile --tag hello_word_project:$version
    
    - name: log in to docker hub
      run: docker login -u ${{ secrets.USER_DOCKER_HUB }} -p ${{ secrets.DOCKERHUB_PASSWORD }} 
    
    - name: push the image to docker hub  
      run: docker push ${{ secrets.USER_DOCKER_HUB }}/hello_word_project:$version
