name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set version to var version
      run: version="${{ github.run_number }}"
    - name: update version to POM file
      run: sed -i 's/<version>.*<\/version>/<version>1.0.$version<\/version>/' pom.xml

    
    - name: Build the Docker image
      run: docker build --build-arg VERSION=$version . --file Dockerfile --tag my-image-name:$version
