name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set version to var version
      run: echo "version=${{ github.run_number }}" >> $GITHUB_ENV

    - name: update version to POM file
      run: sed -i 's/<version>1.0.0<\/version>/<version>1.0.$version<\/version>/' pom.xml
      
    - name: Check version value
      run: echo "version is:$version"

    
    - name: Build the Docker image
      run: docker build --build-arg VERSION=$version . --file Dockerfile --tag ${{ secrets.USER_DOCKER_HUB }}/hello_word_project:$version
    
    - name: log in to docker hub
      run: docker login -u ${{ secrets.USER_DOCKER_HUB }} -p ${{ secrets.PASSWORD_DOCKER_HUB }} 
    
    - name: push the image to docker hub  
      run: docker push ${{ secrets.USER_DOCKER_HUB }}/hello_word_project:$version

    - name: save SSH Key
      run: echo "${{ secrets.AWS_SECRET }}" > new_key.pem

    - name: a  
      run: chmod 600 new_key.pem

    - name: Deploy the image
      run: |
         ssh -o StrictHostKeyChecking=no -i new_key.pem ubuntu@ec2-18-209-227-146.compute-1.amazonaws.com <<EOF
         docker pull ${{ secrets.USER_DOCKER_HUB }}/hello_word_project:$version
         docker stop APPcontainer || true
         docker rm APPcontainer || true
         docker run -d --name APPcontainer ${{ secrets.USER_DOCKER_HUB }}/hello_word_project:$version
         EOF

